/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as DiyRouteImport } from './routes/diy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as JoprothoRouteImport } from './routes/joprotho'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as NextRouteImport } from './routes/next'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as UnlockRouteImport } from './routes/unlock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const DiyRoute = DiyRouteImport.update({
  id: '/diy',
  path: '/diy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const JoprothoRoute = JoprothoRouteImport.update({
  id: '/joprotho',
  path: '/joprotho',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const NextRoute = NextRouteImport.update({
  id: '/next',
  path: '/next',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/confirm': typeof ConfirmRoute
  '/diy': typeof DiyRoute
  '/help': typeof HelpRoute
  '/joprotho': typeof JoprothoRoute
  '/learn': typeof LearnRoute
  '/next': typeof NextRoute
  '/report': typeof ReportRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/unlock': typeof UnlockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/confirm': typeof ConfirmRoute
  '/diy': typeof DiyRoute
  '/help': typeof HelpRoute
  '/joprotho': typeof JoprothoRoute
  '/learn': typeof LearnRoute
  '/next': typeof NextRoute
  '/report': typeof ReportRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/unlock': typeof UnlockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/confirm': typeof ConfirmRoute
  '/diy': typeof DiyRoute
  '/help': typeof HelpRoute
  '/joprotho': typeof JoprothoRoute
  '/learn': typeof LearnRoute
  '/next': typeof NextRoute
  '/report': typeof ReportRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/unlock': typeof UnlockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/confirm'
    | '/diy'
    | '/help'
    | '/joprotho'
    | '/learn'
    | '/next'
    | '/report'
    | '/scan'
    | '/settings'
    | '/tracking'
    | '/unlock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/confirm'
    | '/diy'
    | '/help'
    | '/joprotho'
    | '/learn'
    | '/next'
    | '/report'
    | '/scan'
    | '/settings'
    | '/tracking'
    | '/unlock'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/confirm'
    | '/diy'
    | '/help'
    | '/joprotho'
    | '/learn'
    | '/next'
    | '/report'
    | '/scan'
    | '/settings'
    | '/tracking'
    | '/unlock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ConfirmRoute: typeof ConfirmRoute
  DiyRoute: typeof DiyRoute
  HelpRoute: typeof HelpRoute
  JoprothoRoute: typeof JoprothoRoute
  LearnRoute: typeof LearnRoute
  NextRoute: typeof NextRoute
  ReportRoute: typeof ReportRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  TrackingRoute: typeof TrackingRoute
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diy': {
      id: '/diy'
      path: '/diy'
      fullPath: '/diy'
      preLoaderRoute: typeof DiyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joprotho': {
      id: '/joprotho'
      path: '/joprotho'
      fullPath: '/joprotho'
      preLoaderRoute: typeof JoprothoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next': {
      id: '/next'
      path: '/next'
      fullPath: '/next'
      preLoaderRoute: typeof NextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  ConfirmRoute: ConfirmRoute,
  DiyRoute: DiyRoute,
  HelpRoute: HelpRoute,
  JoprothoRoute: JoprothoRoute,
  LearnRoute: LearnRoute,
  NextRoute: NextRoute,
  ReportRoute: ReportRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  TrackingRoute: TrackingRoute,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
